### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Spar9a** [Spar9a/FMatrice#1]
### Task List
- [x] Добавление методов решения
- [x] Написать алгоритм определения размера матрицы
- [x] Изучение двумерного массива данных
- [x] Внедрение его в нашу программу
- [x] Различные типы матриц
- [x] Очистку массива после выполнения функции
